### ISSUE TITLE
Error on windows

### ISSUE THREAD

**Issue by djidan10** [amueller/gco_python#13]
```
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    from pygco import cut_simple, cut_from_graph
ImportError: No module named 'pygco'
```

Thanks

**Comment by amueller** [comment]
how did you install it?

**Comment by mohammadkamalzare** [comment]
I have the same problem , 
first I build gco-v3.0 in matlab (run GCO_BuildLib)
second I put the gco-v3.0 root address in setup.py and third execute python setup.py build
but when I run example.py , it goes to same error as djidan10

**Comment by amueller** [comment]
@mohammadkamalzare you also need to ``python setup.py install`` or you need to do ``pip install -e .`` to add the folder to your pythonpath.

**Comment by mohammadkamalzare** [comment]
@amueller  Thanks a lot , it works.

**Comment by amueller** [comment]
closing for no reply on original issue.

**Comment by aminevsaziz** [comment]
@amueller @mohammadkamalzare @djidan10 can anyone explain the steps in details.. i'am new to compiling and building in windows environment.
Thanks in advance.
