### ISSUE TITLE
update setup

### ISSUE THREAD

**Issue by Borda** [amueller/gco_python#17]
Hello, may I have a friendly advice for the setup, you should include also setup require since it may fail while installing to empty environment, you can take an inspiration from the [alternative GCO wrapper](https://github.com/Borda/pyGCO).

**Comment by amueller** [comment]
PR welcome ;)

**Comment by amueller** [comment]
Why did you rewrite the wrappers? Don't you like OpenGM2?

**Comment by Borda** [comment]
I did not rewrite it, I just adopt it (the rewriting job was done by someone else) and made some particular changes such as the setup, tests, etc. :)

**Comment by amueller** [comment]
Hey.
Sorry I didn't follow up. Maybe we should try merging these projects?

**Comment by Borda** [comment]
Well, I think that it would be nice to have only one wrapper for the GCO so a user does not need to think much which one to chose or try as first one... I see that for this wrapper there are still a few todos compare to the other wrapper which seems to be complete... on the other hand, I am not the owner of the other one so a merging is not up to me to make such decision...
