### ISSUE TITLE
Source code dead link

### ISSUE THREAD

**Issue by mjstevens777** [amueller/gco_python#18]
It looks like the original source code download at <http://vision.csd.uwo.ca/code/gco-v3.0.zip> has moved. I'm not sure if this is a temporary or a permanent issue.

**Comment by Borda** [comment]
It seems that all Vision lab's page is down...
just in case, the code is also here - https://github.com/Borda/pyGCO/tree/master/gco_source

**Comment by amueller** [comment]
@Borda do you have written permission by Olga Veksler to redistribute the code or are you breaking the license?

**Comment by amueller** [comment]
It explicitly says "Only Olga Veksler has the right to redistribute this code, unless expressed permission is given otherwise"

**Comment by Borda** [comment]
@amueller in such case, I do not have anything like this... :(

**Comment by amueller** [comment]
I was not able to obtain anything, which is why I download it on demand from the website, which is the only legal thing do to (and also possibly kinda sketchy).

**Comment by amueller** [comment]
The copyright is actually with the university, I think, and she can't simply change it.

**Comment by Borda** [comment]
I recall that one contributor made a small change in the C code so that is the reason why we have it in the repository...

**Comment by amueller** [comment]
That doesn't make it legal though...

**Comment by amueller** [comment]
Have you looked at opengm? I'm pretty sure they have their own
implementation. Opencv does, too

**Comment by kunal0895** [comment]
http://mouse.cs.uwaterloo.ca/code/gco-v3.0.zip

For this zip file, this link worked. Using pip for installing this fails since it refers to the previous link and returns a 404.

**Comment by NarayanSchuetz** [comment]
It's dead again ;)! 

That's why conferences and journals should make it mandatory that code not only be available but be available in a public repository and not some University site that may or may not exist in the next few years to come.

**Comment by amueller** [comment]
I recommend using the OpenGM implementation - at least that was a good idea last time I checked quite a while ago.

**Comment by amueller** [comment]
Well there's a listing here, but it links to the dead link: https://vision.cs.uwaterloo.ca/code/

**Comment by Borda** [comment]
> I recommend using the OpenGM implementation - at least that was a good idea last time I checked quite a while ago.

do you have example of a suitable replacement, which function from OpenGM would you recommend?

**Comment by NarayanSchuetz** [comment]
I don't think OpenGM implements their extended Alpha-Extension / A-B-Swap with label costs. 
I mean technically you are allowed to use their source code under their conditions but not allowed to redistribute it. 

In the end it's very unlikely that anything would happen as the work most likely was created under employment by the University of Waterloo and thus belongs to them and was meant for non-commercial public access in the first place.

For custom implementations based on min-cuts I had success with this [python wrapper](https://github.com/pmneila/PyMaxflow) based on Vladimir Kolmogorov's  C++ source.

**Comment by amueller** [comment]
The alpha-extension and a-b-swap are relatively simple to implement based if you have the graphcuts. Maybe OpenCV would be a suitable implementation?

I also have PyQPBO which is more general but basically as fast as GCO:
https://github.com/pystruct/pyqpbo

**Comment by amueller** [comment]
fixed in #23.
