### ISSUE TITLE
Cannot install with pip3

### ISSUE THREAD

**Issue by lvgeng** [amueller/gco_python#21]
https://github.com/cgearhart/DepthFromDefocus
This get me here.

I ran 

pip3 install git+git://github.com/amueller/gco_python

got these:
Collecting git+git://github.com/amueller/gco_python
  Cloning git://github.com/amueller/gco_python to /tmp/pip-x5y6yeo2-build
Collecting cython (from pygco==0.0.1)
  Using cached https://files.pythonhosted.org/packages/b2/20/46a78072ecd4fda072c3791a257b03af99b64673671663067d18bc4935ec/Cython-0.29.7-cp36-cp36m-manylinux1_x86_64.whl
Collecting numpy (from pygco==0.0.1)
  Using cached https://files.pythonhosted.org/packages/c1/e2/4db8df8f6cddc98e7d7c537245ef2f4e41a1ed17bf0c3177ab3cc6beac7f/numpy-1.16.3-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: cython, numpy, pygco
  Running setup.py install for pygco ... done
Successfully installed cython-0.29.7 numpy-1.16.3 pygco-0.0.1

 However the package is not recognized.

from gco_python.pygco import cut_simple

ModuleNotFoundError: No module named 'gco_python'

Bug?

**Comment by Borda** [comment]
note that the package name is `pygco` so you should call it `from pygco import cut_simple`
